//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.StrazhDeviceSDK.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.StrazhDeviceSDK.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Violation schedule.
        /// </summary>
        public static string AccessScheduleOffense {
            get {
                return ResourceManager.GetString("AccessScheduleOffense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always closed.
        /// </summary>
        public static string AlwaysClosed {
            get {
                return ResourceManager.GetString("AlwaysClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always open.
        /// </summary>
        public static string AlwaysOpen {
            get {
                return ResourceManager.GetString("AlwaysOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open another door lock.
        /// </summary>
        public static string AnotherDoorOpen {
            get {
                return ResourceManager.GetString("AnotherDoorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black list.
        /// </summary>
        public static string BlackList {
            get {
                return ResourceManager.GetString("BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller is busy.
        /// </summary>
        public static string ControllerBusy {
            get {
                return ResourceManager.GetString("ControllerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller can not be found.
        /// </summary>
        public static string ControllerNotFound {
            get {
                return ResourceManager.GetString("ControllerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to controller configuration was not found.
        /// </summary>
        public static string ControllerNotFoundInConfig {
            get {
                return ResourceManager.GetString("ControllerNotFoundInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not close the castle, located in Mode ALWAYS OPEN.
        /// </summary>
        public static string CouldNotOpenLockInAlwaysOpenMode {
            get {
                return ResourceManager.GetString("CouldNotOpenLockInAlwaysOpenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to debts.
        /// </summary>
        public static string Debts {
            get {
                return ResourceManager.GetString("Debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrance.
        /// </summary>
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiration.
        /// </summary>
        public static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only fingerprint.
        /// </summary>
        public static string FingerprintOnly {
            get {
                return ResourceManager.GetString("FingerprintOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compulsion.
        /// </summary>
        public static string Forcing {
            get {
                return ResourceManager.GetString("Forcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frozen.
        /// </summary>
        public static string Frozen {
            get {
                return ResourceManager.GetString("Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guests {
            get {
                return ResourceManager.GetString("Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect method of opening the lock.
        /// </summary>
        public static string IncorectLockOpenMode {
            get {
                return ResourceManager.GetString("IncorectLockOpenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        public static string IncorectPassword {
            get {
                return ResourceManager.GetString("IncorectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login.
        /// </summary>
        public static string IncorrectLogin {
            get {
                return ResourceManager.GetString("IncorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password pass.
        /// </summary>
        public static string IncorrectPasscardPassword {
            get {
                return ResourceManager.GetString("IncorrectPasscardPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep an open.
        /// </summary>
        public static string KeepOpen {
            get {
                return ResourceManager.GetString("KeepOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle 1 + 2.
        /// </summary>
        public static string Lock12 {
            get {
                return ResourceManager.GetString("Lock12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle 1 + 2 + 3.
        /// </summary>
        public static string Lock123 {
            get {
                return ResourceManager.GetString("Lock123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle 1 + 2 + 3 + 4.
        /// </summary>
        public static string Lock1234 {
            get {
                return ResourceManager.GetString("Lock1234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle 1 + 3 and 2 + 4.
        /// </summary>
        public static string Lock1324 {
            get {
                return ResourceManager.GetString("Lock1324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle 1 + 4 and 2 + 3.
        /// </summary>
        public static string Lock1423 {
            get {
                return ResourceManager.GetString("Lock1423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle 2 + 3 + 4.
        /// </summary>
        public static string Lock234 {
            get {
                return ResourceManager.GetString("Lock234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle 3 + 4.
        /// </summary>
        public static string Lock34 {
            get {
                return ResourceManager.GetString("Lock34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle in the &apos;Hacking&apos;.
        /// </summary>
        public static string LockBreaking {
            get {
                return ResourceManager.GetString("LockBreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle in &apos;closed&apos;.
        /// </summary>
        public static string LockClosed {
            get {
                return ResourceManager.GetString("LockClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to castle in configuration was not found.
        /// </summary>
        public static string LockNotFoundInConfig {
            get {
                return ResourceManager.GetString("LockNotFoundInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock settings does not support skipping &apos;Coercion&apos;.
        /// </summary>
        public static string LockSettingNotSupportForcing {
            get {
                return ResourceManager.GetString("LockSettingNotSupportForcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lost.
        /// </summary>
        public static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternal.
        /// </summary>
        public static string Maternal {
            get {
                return ResourceManager.GetString("Maternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer Unlock.
        /// </summary>
        public static string MultiplayerUnlock {
            get {
                return ResourceManager.GetString("MultiplayerUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two-door controller.
        /// </summary>
        public static string NC002 {
            get {
                return ResourceManager.GetString("NC002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four controller.
        /// </summary>
        public static string NC004 {
            get {
                return ResourceManager.GetString("NC004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single-door controller.
        /// </summary>
        public static string NC101 {
            get {
                return ResourceManager.GetString("NC101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access rights.
        /// </summary>
        public static string NoAccessPermissions {
            get {
                return ResourceManager.GetString("NoAccessPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        public static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No communication with the controller &quot;{0}&quot;. {1}&quot;.
        /// </summary>
        public static string NoLinkWithController {
            get {
                return ResourceManager.GetString("NoLinkWithController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal.
        /// </summary>
        public static string Normals {
            get {
                return ResourceManager.GetString("Normals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the configuration can not be found.
        /// </summary>
        public static string NotFoundInConfig {
            get {
                return ResourceManager.GetString("NotFoundInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation canceled.
        /// </summary>
        public static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated passage in the zone.
        /// </summary>
        public static string PassbackToZone {
            get {
                return ResourceManager.GetString("PassbackToZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Passcard {
            get {
                return ResourceManager.GetString("Passcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skipping disabled.
        /// </summary>
        public static string PasscardBlocked {
            get {
                return ResourceManager.GetString("PasscardBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map and fingerprint.
        /// </summary>
        public static string PasscardFingerprint {
            get {
                return ResourceManager.GetString("PasscardFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First map.
        /// </summary>
        public static string PasscardFirst {
            get {
                return ResourceManager.GetString("PasscardFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string PasscardNumber {
            get {
                return ResourceManager.GetString("PasscardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of card.
        /// </summary>
        public static string PasscardType {
            get {
                return ResourceManager.GetString("PasscardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pass has expired or has not come.
        /// </summary>
        public static string PasscardValidityExpired {
            get {
                return ResourceManager.GetString("PasscardValidityExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First password.
        /// </summary>
        public static string PasswordFirst {
            get {
                return ResourceManager.GetString("PasswordFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password Only.
        /// </summary>
        public static string PasswordOnly {
            get {
                return ResourceManager.GetString("PasswordOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Card.
        /// </summary>
        public static string PasswordOrCard {
            get {
                return ResourceManager.GetString("PasswordOrCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password card or fingerprint.
        /// </summary>
        public static string PasswordOrCardOrFingerprint {
            get {
                return ResourceManager.GetString("PasswordOrCardOrFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrol.
        /// </summary>
        public static string Patrol {
            get {
                return ResourceManager.GetString("Patrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader 1 or 3 Entrance, Reader 2 or 4 - Exit.
        /// </summary>
        public static string Reader13InReader24Out {
            get {
                return ResourceManager.GetString("Reader13InReader24Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader 1 - Entrance, Reader 2 - Exit.
        /// </summary>
        public static string Reader1InReader2Out {
            get {
                return ResourceManager.GetString("Reader1InReader2Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader 3 - Entrance, Reader 4 - Exit.
        /// </summary>
        public static string Reader3InReader4Out {
            get {
                return ResourceManager.GetString("Reader3InReader4Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remotely.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe room.
        /// </summary>
        public static string SafeRoom {
            get {
                return ResourceManager.GetString("SafeRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time-out.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under the protection of.
        /// </summary>
        public static string UnderProtection {
            get {
                return ResourceManager.GetString("UnderProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown cause.
        /// </summary>
        public static string UnknownReason {
            get {
                return ResourceManager.GetString("UnknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user was blocked.
        /// </summary>
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is illegal.
        /// </summary>
        public static string UserIsIllegal {
            get {
                return ResourceManager.GetString("UserIsIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already logged.
        /// </summary>
        public static string UserLogged {
            get {
                return ResourceManager.GetString("UserLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usual.
        /// </summary>
        public static string Usuals {
            get {
                return ResourceManager.GetString("Usuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vip.
        /// </summary>
        public static string Vip {
            get {
                return ResourceManager.GetString("Vip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for confirmation of passage.
        /// </summary>
        public static string WaitPassConfirm {
            get {
                return ResourceManager.GetString("WaitPassConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write access to the controller schedules &quot;{0}&quot;.
        /// </summary>
        public static string WriteAccessSchedulesOnController {
            get {
                return ResourceManager.GetString("WriteAccessSchedulesOnController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A write access to the controller schedules &quot;{0}&quot; canceled.
        /// </summary>
        public static string WriteAccessSchedulesOnControllerCanceled {
            get {
                return ResourceManager.GetString("WriteAccessSchedulesOnControllerCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record locks passwords on the controller &quot;{0}&quot;.
        /// </summary>
        public static string WriteLockPasswordsOnController {
            get {
                return ResourceManager.GetString("WriteLockPasswordsOnController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A write lock password to the controller &quot;{0}&quot; canceled.
        /// </summary>
        public static string WriteLockPasswordsOnControllerCanceled {
            get {
                return ResourceManager.GetString("WriteLockPasswordsOnControllerCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record passes to the controller &quot;{0}&quot;.
        /// </summary>
        public static string WritePasscardsOnController {
            get {
                return ResourceManager.GetString("WritePasscardsOnController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong ID.
        /// </summary>
        public static string WrongId {
            get {
                return ResourceManager.GetString("WrongId", resourceCulture);
            }
        }
    }
}
