<?xml version="1.0" encoding="utf-8"?><Database Name="SKDImirator" Class="SKDImitatorDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=SKDImirator;Integrated Security=True" SettingsObjectName="GKImitator.Properties.Settings" SettingsPropertyName="SKDImiratorConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Devices" Member="Devices">
    <Type Name="Devices">
      <Column Name="UID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastJournalNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeIntervalHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>