using Infrastructure.Common;
using System.Linq;
using Infrastructure.Common.Windows.ViewModels;
using ReportsModule.Views;
using System.Windows.Documents;
using System.Windows.Markup;
using System.IO;
using System.Collections.Generic;
using FiresecAPI.Models;
using System;

namespace ReportsModule.ViewModels
{
	public class ReportsViewModel : ViewPartViewModel
	{
		public ReportsViewModel()
		{
			RefreshCommand = new RelayCommand(OnRefresh, CanRefresh);
			FilterCommand = new RelayCommand(OnFilter, CanFilter);
		}


		public List<ReportType> AvailableReportTypes
		{
			get { return Enum.GetValues(typeof(ReportType)).Cast<ReportType>().ToList(); }
		}

		private FlowDocument _document;
		public FlowDocument Document
		{
			get { return _document; }
			private set
			{
				_document = value;
				OnPropertyChanged("Document");
			}
		}

		private ReportType? _selectedReportName;
		public ReportType? SelectedReportName
		{
			get { return _selectedReportName; }
			set
			{
				_selectedReportName = value;
				OnPropertyChanged("SelectedReportName");
				OnPropertyChanged("IsJournalReport");
				RefreshCommand.Execute();
			}
		}

		public RelayCommand RefreshCommand { get; private set; }
		private void OnRefresh()
		{
			string flowDoucment = @"<FlowDocument xmlns=""http://schemas.microsoft.com/winfx/2006/xaml/presentation"" xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml"" xmlns:s=""clr-namespace:System;assembly=mscorlib"" ColumnWidth=""793.700787401575"" PageHeight=""1122.51968503937"" PageWidth=""793.700787401575"">
		<FlowDocument.Resources>
			<Style x:Key=""dataRowStyle"" TargetType=""TableRowGroup"">
				<Style.Resources>
					<ResourceDictionary />
				</Style.Resources>
				<Setter Property=""TextElement.FontSize"">
					<Setter.Value>
						<s:Double>12</s:Double>
					</Setter.Value>
				</Setter>
			</Style>
			<Style x:Key=""headerFooterRowStyle"" TargetType=""TableRowGroup"">
				<Style.Resources>
					<ResourceDictionary />
				</Style.Resources>
				<Setter Property=""TextElement.FontWeight"">
					<Setter.Value>
						<FontWeight>SemiBold</FontWeight>
					</Setter.Value>
				</Setter>
				<Setter Property=""TextElement.FontSize"">
					<Setter.Value>
						<s:Double>16</s:Double>
					</Setter.Value>
				</Setter>
				<Setter Property=""TextElement.Background"">
					<Setter.Value>
						<SolidColorBrush>#FFD3D3D3</SolidColorBrush>
					</Setter.Value>
				</Setter>
			</Style>
			<Style x:Key=""{x:Type TableCell}"" TargetType=""TableCell"">
				<Style.Resources>
					<ResourceDictionary />
				</Style.Resources>
				<Setter Property=""Block.Padding"">
					<Setter.Value>
						<Thickness>3.77952755905512,3.77952755905512,3.77952755905512,3.77952755905512</Thickness>
					</Setter.Value>
				</Setter>
				<Setter Property=""Block.BorderBrush"">
					<Setter.Value>
						<SolidColorBrush>#FF000000</SolidColorBrush>
					</Setter.Value>
				</Setter>
				<Setter Property=""Block.BorderThickness"">
					<Setter.Value>
						<Thickness>0.377952755905512,0.377952755905512,0.377952755905512,0.377952755905512</Thickness>
					</Setter.Value>
				</Setter>
			</Style>
		</FlowDocument.Resources>
		<Section BreakPageBefore=""True"" FontSize=""12"" Padding=""80,20,40,10"">
			<Paragraph>Reports whose headers/colums and data/rows are created on execution time.</Paragraph>
			<Paragraph>Report 1</Paragraph>
			<Table BorderBrush=""#FF000000"" BorderThickness=""0.755905511811024,0.755905511811024,0.755905511811024,0.755905511811024"" CellSpacing=""0"">
				<TableRowGroup>
					<TableRowGroup.Style>
						<Style TargetType=""TableRowGroup"">
							<Style.Resources>
								<ResourceDictionary />
							</Style.Resources>
							<Setter Property=""TextElement.FontWeight"">
								<Setter.Value>
									<FontWeight>SemiBold</FontWeight>
								</Setter.Value>
							</Setter>
							<Setter Property=""TextElement.FontSize"">
								<Setter.Value>
									<s:Double>16</s:Double>
								</Setter.Value>
							</Setter>
							<Setter Property=""TextElement.Background"">
								<Setter.Value>
									<SolidColorBrush>#FFD3D3D3</SolidColorBrush>
								</Setter.Value>
							</Setter>
						</Style>
					</TableRowGroup.Style>
					<TableRow>
						<TableCell>
							<Paragraph>Service</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Amount</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Price</Paragraph>
						</TableCell>
					</TableRow>
				</TableRowGroup>
				<TableRowGroup>
					<TableRowGroup.Style>
						<Style TargetType=""TableRowGroup"">
							<Style.Resources>
								<ResourceDictionary />
							</Style.Resources>
							<Setter Property=""TextElement.FontSize"">
								<Setter.Value>
									<s:Double>12</s:Double>
								</Setter.Value>
							</Setter>
						</Style>
					</TableRowGroup.Style>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє0</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>0</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>0 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє1</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє2</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє3</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє4</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє5</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>10</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє6</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>12</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє7</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>14</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє8</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>16</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє9</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>18</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє10</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>20</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>10 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє11</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>22</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>11 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє12</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>24</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>12 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє13</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>26</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>13 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>Service oferted. NВє14</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>28</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>14 в‚¬</Paragraph>
						</TableCell>
					</TableRow>
				</TableRowGroup>
			</Table>
			<Paragraph>Report 2</Paragraph>
			<Table BorderBrush=""#FF000000"" BorderThickness=""0.755905511811024,0.755905511811024,0.755905511811024,0.755905511811024"" CellSpacing=""0"">
				<TableRowGroup>
					<TableRowGroup.Style>
						<Style TargetType=""TableRowGroup"">
							<Style.Resources>
								<ResourceDictionary />
							</Style.Resources>
							<Setter Property=""TextElement.FontWeight"">
								<Setter.Value>
									<FontWeight>SemiBold</FontWeight>
								</Setter.Value>
							</Setter>
							<Setter Property=""TextElement.FontSize"">
								<Setter.Value>
									<s:Double>16</s:Double>
								</Setter.Value>
							</Setter>
							<Setter Property=""TextElement.Background"">
								<Setter.Value>
									<SolidColorBrush>#FFD3D3D3</SolidColorBrush>
								</Setter.Value>
							</Setter>
						</Style>
					</TableRowGroup.Style>
					<TableRow>
						<TableCell>
							<Paragraph>Position</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>EAN</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Count</Paragraph>
						</TableCell>
					</TableRow>
				</TableRowGroup>
				<TableRowGroup>
					<TableRowGroup.Style>
						<Style TargetType=""TableRowGroup"">
							<Style.Resources>
								<ResourceDictionary />
							</Style.Resources>
							<Setter Property=""TextElement.FontSize"">
								<Setter.Value>
									<s:Double>12</s:Double>
								</Setter.Value>
							</Setter>
						</Style>
					</TableRowGroup.Style>
					<TableRow>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0001</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0002</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0003</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0004</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0005</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0006</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0007</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0008</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0009</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>10</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0010</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>11</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0011</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>12</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0012</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>13</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0013</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>14</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0014</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>15</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0015</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>16</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0016</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>17</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0017</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>18</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0018</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>19</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0019</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>20</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0020</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>21</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0021</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>22</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0022</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>23</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0023</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>24</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0024</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>25</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0025</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>26</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0026</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>27</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0027</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>28</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0028</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>29</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0029</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>30</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0030</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>31</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0031</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>32</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0032</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>33</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0033</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>34</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0034</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>35</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0035</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>36</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0036</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>37</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0037</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>38</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0038</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>39</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0039</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>40</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0040</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>41</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0041</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>42</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0042</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>43</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0043</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>44</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0044</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>45</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0045</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>46</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0046</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>47</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0047</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>48</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0048</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>49</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0049</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>50</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0050</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>51</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0051</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>52</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0052</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>53</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0053</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>54</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0054</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>55</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0055</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>56</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0056</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>57</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0057</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>58</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0058</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>59</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0059</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>60</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0060</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>61</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0061</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>62</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0062</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>63</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0063</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>64</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0064</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>65</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0065</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>66</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0066</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>67</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0067</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>68</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0068</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>69</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0069</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>70</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0070</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>71</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0071</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>72</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0072</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>73</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0073</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>74</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0074</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>75</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0075</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>76</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0076</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>77</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0077</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>78</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0078</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>79</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0079</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>80</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0080</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>81</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0081</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>82</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0082</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>83</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0083</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>84</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0084</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>85</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0085</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>86</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0086</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>87</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0087</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>88</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0088</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>89</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0089</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>90</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0090</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>91</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0091</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>92</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0092</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>93</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0093</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>94</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0094</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>95</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0095</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>96</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0096</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>97</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0097</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>98</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0098</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>99</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0099</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>100</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0100</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>101</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0101</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>102</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0102</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>103</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0103</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>104</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0104</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>105</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0105</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>106</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0106</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>107</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0107</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>108</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0108</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>109</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0109</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>110</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0110</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>111</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0111</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>112</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0112</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>113</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0113</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>114</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0114</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>115</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0115</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>116</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0116</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>117</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0117</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>118</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0118</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>119</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0119</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>120</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0120</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>121</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0121</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>122</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0122</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>124</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0124</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>125</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0125</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>126</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0126</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>127</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0127</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>128</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0128</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>129</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0129</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>130</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0130</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>131</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0131</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>132</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0132</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>133</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0133</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>134</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0134</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>135</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0135</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>136</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0136</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>137</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0137</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>138</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0138</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>139</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0139</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>140</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0140</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>141</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0141</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>142</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0142</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>143</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0143</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>144</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0144</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>145</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0145</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>146</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0146</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>147</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0147</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>148</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0148</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>149</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0149</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>150</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0150</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>151</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0151</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>152</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0152</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>153</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0153</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>154</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0154</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>155</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0155</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>156</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0156</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>157</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0157</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>158</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0158</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>159</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0159</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>160</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0160</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>161</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0161</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>162</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0162</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>163</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0163</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>164</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0164</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>165</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0165</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>166</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0166</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>167</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0167</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>168</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0168</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>169</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0169</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>170</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0170</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>171</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0171</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>172</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0172</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>173</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0173</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>174</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0174</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>175</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0175</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>176</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0176</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>177</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0177</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>178</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0178</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>7</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>179</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0179</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>180</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0180</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>181</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0181</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>182</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0182</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>183</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0183</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>184</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0184</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>185</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0185</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>186</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0186</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>187</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0187</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>188</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0188</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>189</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0189</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>190</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0190</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>5</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>191</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0191</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>2</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>192</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0192</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>6</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>193</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0193</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>194</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0194</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>195</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0195</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>3</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>196</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0196</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>8</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>197</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0197</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>9</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>198</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0198</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>199</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0199</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>4</Paragraph>
						</TableCell>
					</TableRow>
					<TableRow>
						<TableCell>
							<Paragraph>200</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>Item 0200</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>123456790123</Paragraph>
						</TableCell>
						<TableCell>
							<Paragraph>1</Paragraph>
						</TableCell>
					</TableRow>
				</TableRowGroup>
			</Table>
		</Section>
	</FlowDocument>";
			Document = (FlowDocument)XamlReader.Parse(flowDoucment);
		}
		private bool CanRefresh()
		{
			return true;
		}

		public RelayCommand FilterCommand { get; private set; }
		private void OnFilter()
		{
		}
		private bool CanFilter()
		{
			return SelectedReportName == ReportType.ReportJournal;
		}

	}
}