//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3634
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=2.0.50727.3038.
// 

namespace Rubezh2010
{
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class bit
	{

		private string noField;

		private string valueField;

		private string valField;

		private string inverseField;

		private string classField;

		private string typeField;

		private string idField;

		private string manualResetField;

		private string manualResetField1;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string no
		{
			get
			{
				return this.noField;
			}
			set
			{
				this.noField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string val
		{
			get
			{
				return this.valField;
			}
			set
			{
				this.valField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string inverse
		{
			get
			{
				return this.inverseField;
			}
			set
			{
				this.inverseField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @class
		{
			get
			{
				return this.classField;
			}
			set
			{
				this.classField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string manualReset
		{
			get
			{
				return this.manualResetField;
			}
			set
			{
				this.manualResetField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string ManualReset
		{
			get
			{
				return this.manualResetField1;
			}
			set
			{
				this.manualResetField1 = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class driverConfig
	{

		private driverConfigDictionary[] dictionaryField;

		private driverConfigDeviceTablesDeviceTable[] deviceTablesField;

		private driverConfigEventsEvent[] eventsField;

		private bit[] panelStatesField;

		private driverConfigDeviceStatesDeviceState[] deviceStatesField;

		private driverConfigDevicePropInfosDevicePropInfo[] devicePropInfosField;

		private string validCharsField;

		private string timeSliceTypeField;

		private string connectionLostDelayField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("dictionary", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public driverConfigDictionary[] dictionary
		{
			get
			{
				return this.dictionaryField;
			}
			set
			{
				this.dictionaryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("deviceTable", typeof(driverConfigDeviceTablesDeviceTable), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public driverConfigDeviceTablesDeviceTable[] deviceTables
		{
			get
			{
				return this.deviceTablesField;
			}
			set
			{
				this.deviceTablesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("event", typeof(driverConfigEventsEvent), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public driverConfigEventsEvent[] events
		{
			get
			{
				return this.eventsField;
			}
			set
			{
				this.eventsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("bit", typeof(bit), IsNullable = false)]
		public bit[] panelStates
		{
			get
			{
				return this.panelStatesField;
			}
			set
			{
				this.panelStatesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("deviceState", typeof(driverConfigDeviceStatesDeviceState), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public driverConfigDeviceStatesDeviceState[] deviceStates
		{
			get
			{
				return this.deviceStatesField;
			}
			set
			{
				this.deviceStatesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlArrayItemAttribute("devicePropInfo", typeof(driverConfigDevicePropInfosDevicePropInfo), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
		public driverConfigDevicePropInfosDevicePropInfo[] devicePropInfos
		{
			get
			{
				return this.devicePropInfosField;
			}
			set
			{
				this.devicePropInfosField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string validChars
		{
			get
			{
				return this.validCharsField;
			}
			set
			{
				this.validCharsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string timeSliceType
		{
			get
			{
				return this.timeSliceTypeField;
			}
			set
			{
				this.timeSliceTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string connectionLostDelay
		{
			get
			{
				return this.connectionLostDelayField;
			}
			set
			{
				this.connectionLostDelayField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigDictionary
	{

		private bit[] bitField;

		private string nameField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("bit")]
		public bit[] bit
		{
			get
			{
				return this.bitField;
			}
			set
			{
				this.bitField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigDeviceTablesDeviceTable
	{

		private driverConfigDeviceTablesDeviceTableDetalization[] detalizationField;

		private string tableTypeField;

		private string recordTypeField;

		private string deviceDriverIDField;

		private string deviceClassIDField;

		private string deviceDriverAliasField;

		private string deviceNameField;

		private string maxOutputDeviceCountField;

		private string shortNameField;

		private string isOutDevice2Field;

		private string ignoreInZoneStateField;

		private string iconField;

		private string baseDeviceField;

		private string categoryField;

		private string addressMaskField;

		private string isOutDeviceField;

		private string typeField;

		private string hasSmokeChanelField;

		private string ignorableField;

		private string hasTempChanelField;

		private string subTypeField;

		private string noAddressField;

		private string singleField;

		private string singleInZoneField;

		private string addressGroupField;

		private string minOutputDeviceCountField;

		private string addressGroupField1;

		private string hasPressureChanelField;

		private string deviceCountField;

		private string childDriverIDField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("detalization", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public driverConfigDeviceTablesDeviceTableDetalization[] detalization
		{
			get
			{
				return this.detalizationField;
			}
			set
			{
				this.detalizationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string tableType
		{
			get
			{
				return this.tableTypeField;
			}
			set
			{
				this.tableTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string recordType
		{
			get
			{
				return this.recordTypeField;
			}
			set
			{
				this.recordTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string deviceDriverID
		{
			get
			{
				return this.deviceDriverIDField;
			}
			set
			{
				this.deviceDriverIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string deviceClassID
		{
			get
			{
				return this.deviceClassIDField;
			}
			set
			{
				this.deviceClassIDField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string deviceDriverAlias
		{
			get
			{
				return this.deviceDriverAliasField;
			}
			set
			{
				this.deviceDriverAliasField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string deviceName
		{
			get
			{
				return this.deviceNameField;
			}
			set
			{
				this.deviceNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string maxOutputDeviceCount
		{
			get
			{
				return this.maxOutputDeviceCountField;
			}
			set
			{
				this.maxOutputDeviceCountField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string shortName
		{
			get
			{
				return this.shortNameField;
			}
			set
			{
				this.shortNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string IsOutDevice2
		{
			get
			{
				return this.isOutDevice2Field;
			}
			set
			{
				this.isOutDevice2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string IgnoreInZoneState
		{
			get
			{
				return this.ignoreInZoneStateField;
			}
			set
			{
				this.ignoreInZoneStateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Icon
		{
			get
			{
				return this.iconField;
			}
			set
			{
				this.iconField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string BaseDevice
		{
			get
			{
				return this.baseDeviceField;
			}
			set
			{
				this.baseDeviceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string category
		{
			get
			{
				return this.categoryField;
			}
			set
			{
				this.categoryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string addressMask
		{
			get
			{
				return this.addressMaskField;
			}
			set
			{
				this.addressMaskField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string IsOutDevice
		{
			get
			{
				return this.isOutDeviceField;
			}
			set
			{
				this.isOutDeviceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string HasSmokeChanel
		{
			get
			{
				return this.hasSmokeChanelField;
			}
			set
			{
				this.hasSmokeChanelField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string ignorable
		{
			get
			{
				return this.ignorableField;
			}
			set
			{
				this.ignorableField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string HasTempChanel
		{
			get
			{
				return this.hasTempChanelField;
			}
			set
			{
				this.hasTempChanelField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string subType
		{
			get
			{
				return this.subTypeField;
			}
			set
			{
				this.subTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string noAddress
		{
			get
			{
				return this.noAddressField;
			}
			set
			{
				this.noAddressField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Single
		{
			get
			{
				return this.singleField;
			}
			set
			{
				this.singleField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string SingleInZone
		{
			get
			{
				return this.singleInZoneField;
			}
			set
			{
				this.singleInZoneField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string AddressGroup
		{
			get
			{
				return this.addressGroupField;
			}
			set
			{
				this.addressGroupField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string minOutputDeviceCount
		{
			get
			{
				return this.minOutputDeviceCountField;
			}
			set
			{
				this.minOutputDeviceCountField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string addressGroup
		{
			get
			{
				return this.addressGroupField1;
			}
			set
			{
				this.addressGroupField1 = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string HasPressureChanel
		{
			get
			{
				return this.hasPressureChanelField;
			}
			set
			{
				this.hasPressureChanelField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string deviceCount
		{
			get
			{
				return this.deviceCountField;
			}
			set
			{
				this.deviceCountField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string childDriverID
		{
			get
			{
				return this.childDriverIDField;
			}
			set
			{
				this.childDriverIDField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigDeviceTablesDeviceTableDetalization
	{

		private string classField;

		private string stateByteField;

		private string dictionaryField;

		private string sourceField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @class
		{
			get
			{
				return this.classField;
			}
			set
			{
				this.classField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string stateByte
		{
			get
			{
				return this.stateByteField;
			}
			set
			{
				this.stateByteField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string dictionary
		{
			get
			{
				return this.dictionaryField;
			}
			set
			{
				this.dictionaryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string source
		{
			get
			{
				return this.sourceField;
			}
			set
			{
				this.sourceField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigEventsEvent
	{

		private driverConfigEventsEventAlterFor[] alterForField;

		private driverConfigEventsEventDetailsFor[] detailsForField;

		private string rawEventCodeField;

		private string eventClassField;

		private string eventClass1Field;

		private string eventClass2Field;

		private string eventMessageField;

		private string hasDeviceField;

		private string hasPasswordField;

		private string eventClassAllField;

		private string eventClass3Field;

		private string eventClass4Field;

		private string hasLineField;

		private string hasZoneExtField;

		private string hasGap3Field;

		private string eventClass12Field;

		private string eventClass14Field;

		private string eventClass20Field;

		private string eventClass22Field;

		private string eventClass6Field;

		private string eventClass8Field;

		private string eventClass10Field;

		private string eventClass16Field;

		private string eventClass18Field;

		private string eventClass5Field;

		private string eventClass7Field;

		private string eventClass9Field;

		private string eventClass15Field;

		private string eventClass17Field;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("alterFor", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public driverConfigEventsEventAlterFor[] alterFor
		{
			get
			{
				return this.alterForField;
			}
			set
			{
				this.alterForField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("detailsFor", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public driverConfigEventsEventDetailsFor[] detailsFor
		{
			get
			{
				return this.detailsForField;
			}
			set
			{
				this.detailsForField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string rawEventCode
		{
			get
			{
				return this.rawEventCodeField;
			}
			set
			{
				this.rawEventCodeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass
		{
			get
			{
				return this.eventClassField;
			}
			set
			{
				this.eventClassField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass1
		{
			get
			{
				return this.eventClass1Field;
			}
			set
			{
				this.eventClass1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass2
		{
			get
			{
				return this.eventClass2Field;
			}
			set
			{
				this.eventClass2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventMessage
		{
			get
			{
				return this.eventMessageField;
			}
			set
			{
				this.eventMessageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string hasDevice
		{
			get
			{
				return this.hasDeviceField;
			}
			set
			{
				this.hasDeviceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string hasPassword
		{
			get
			{
				return this.hasPasswordField;
			}
			set
			{
				this.hasPasswordField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClassAll
		{
			get
			{
				return this.eventClassAllField;
			}
			set
			{
				this.eventClassAllField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass3
		{
			get
			{
				return this.eventClass3Field;
			}
			set
			{
				this.eventClass3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass4
		{
			get
			{
				return this.eventClass4Field;
			}
			set
			{
				this.eventClass4Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string hasLine
		{
			get
			{
				return this.hasLineField;
			}
			set
			{
				this.hasLineField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string hasZoneExt
		{
			get
			{
				return this.hasZoneExtField;
			}
			set
			{
				this.hasZoneExtField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string hasGap3
		{
			get
			{
				return this.hasGap3Field;
			}
			set
			{
				this.hasGap3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass12
		{
			get
			{
				return this.eventClass12Field;
			}
			set
			{
				this.eventClass12Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass14
		{
			get
			{
				return this.eventClass14Field;
			}
			set
			{
				this.eventClass14Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass20
		{
			get
			{
				return this.eventClass20Field;
			}
			set
			{
				this.eventClass20Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass22
		{
			get
			{
				return this.eventClass22Field;
			}
			set
			{
				this.eventClass22Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass6
		{
			get
			{
				return this.eventClass6Field;
			}
			set
			{
				this.eventClass6Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass8
		{
			get
			{
				return this.eventClass8Field;
			}
			set
			{
				this.eventClass8Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass10
		{
			get
			{
				return this.eventClass10Field;
			}
			set
			{
				this.eventClass10Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass16
		{
			get
			{
				return this.eventClass16Field;
			}
			set
			{
				this.eventClass16Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass18
		{
			get
			{
				return this.eventClass18Field;
			}
			set
			{
				this.eventClass18Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass5
		{
			get
			{
				return this.eventClass5Field;
			}
			set
			{
				this.eventClass5Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass7
		{
			get
			{
				return this.eventClass7Field;
			}
			set
			{
				this.eventClass7Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass9
		{
			get
			{
				return this.eventClass9Field;
			}
			set
			{
				this.eventClass9Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass15
		{
			get
			{
				return this.eventClass15Field;
			}
			set
			{
				this.eventClass15Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventClass17
		{
			get
			{
				return this.eventClass17Field;
			}
			set
			{
				this.eventClass17Field = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigEventsEventAlterFor
	{

		private string tableTypeField;

		private string eventMessageField;

		private string useStateField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string tableType
		{
			get
			{
				return this.tableTypeField;
			}
			set
			{
				this.tableTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string eventMessage
		{
			get
			{
				return this.eventMessageField;
			}
			set
			{
				this.eventMessageField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string useState
		{
			get
			{
				return this.useStateField;
			}
			set
			{
				this.useStateField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigEventsEventDetailsFor
	{

		private string tableTypeField;

		private string dictionaryField;

		private string field5Field;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string tableType
		{
			get
			{
				return this.tableTypeField;
			}
			set
			{
				this.tableTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string dictionary
		{
			get
			{
				return this.dictionaryField;
			}
			set
			{
				this.dictionaryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string field5
		{
			get
			{
				return this.field5Field;
			}
			set
			{
				this.field5Field = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigDeviceStatesDeviceState
	{

		private driverConfigDeviceStatesDeviceStateEnter[] enterField;

		private driverConfigDeviceStatesDeviceStateLeave[] leaveField;

		private string classField;

		private string notForTableTypeField;

		private string nameField;

		private string idField;

		private string bitnoField;

		private string typeField;

		private string bitNoField;

		private string zoneBitNoField;

		private string canResetOnPanelField;

		private string tableTypeField;

		private string intBitnoField;

		private string affectedParentField;

		private string intbitnoField;

		private string inverseField;

		private string manualResetField;

		private string bitsField;

		private string valueField;

		private string bitnoField1;

		private string nameSourceField;

		private string isPrimaryStateField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("enter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public driverConfigDeviceStatesDeviceStateEnter[] enter
		{
			get
			{
				return this.enterField;
			}
			set
			{
				this.enterField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("leave", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public driverConfigDeviceStatesDeviceStateLeave[] leave
		{
			get
			{
				return this.leaveField;
			}
			set
			{
				this.leaveField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @class
		{
			get
			{
				return this.classField;
			}
			set
			{
				this.classField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string notForTableType
		{
			get
			{
				return this.notForTableTypeField;
			}
			set
			{
				this.notForTableTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string ID
		{
			get
			{
				return this.idField;
			}
			set
			{
				this.idField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bitno
		{
			get
			{
				return this.bitnoField;
			}
			set
			{
				this.bitnoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bitNo
		{
			get
			{
				return this.bitNoField;
			}
			set
			{
				this.bitNoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string zoneBitNo
		{
			get
			{
				return this.zoneBitNoField;
			}
			set
			{
				this.zoneBitNoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string CanResetOnPanel
		{
			get
			{
				return this.canResetOnPanelField;
			}
			set
			{
				this.canResetOnPanelField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string tableType
		{
			get
			{
				return this.tableTypeField;
			}
			set
			{
				this.tableTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string intBitno
		{
			get
			{
				return this.intBitnoField;
			}
			set
			{
				this.intBitnoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string AffectedParent
		{
			get
			{
				return this.affectedParentField;
			}
			set
			{
				this.affectedParentField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Intbitno
		{
			get
			{
				return this.intbitnoField;
			}
			set
			{
				this.intbitnoField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string inverse
		{
			get
			{
				return this.inverseField;
			}
			set
			{
				this.inverseField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string ManualReset
		{
			get
			{
				return this.manualResetField;
			}
			set
			{
				this.manualResetField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string bits
		{
			get
			{
				return this.bitsField;
			}
			set
			{
				this.bitsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Bitno
		{
			get
			{
				return this.bitnoField1;
			}
			set
			{
				this.bitnoField1 = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string nameSource
		{
			get
			{
				return this.nameSourceField;
			}
			set
			{
				this.nameSourceField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string IsPrimaryState
		{
			get
			{
				return this.isPrimaryStateField;
			}
			set
			{
				this.isPrimaryStateField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigDeviceStatesDeviceStateEnter
	{

		private string event1Field;

		private string eventField;

		private string event8Field;

		private string event10Field;

		private string event3Field;

		private string event6Field;

		private string zoneEventField;

		private string zoneEvent2Field;

		private string event4Field;

		private string event2Field;

		private string event20Field;

		private string event16Field;

		private string event24Field;

		private string event12Field;

		private string event14Field;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event1
		{
			get
			{
				return this.event1Field;
			}
			set
			{
				this.event1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @event
		{
			get
			{
				return this.eventField;
			}
			set
			{
				this.eventField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event8
		{
			get
			{
				return this.event8Field;
			}
			set
			{
				this.event8Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event10
		{
			get
			{
				return this.event10Field;
			}
			set
			{
				this.event10Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event3
		{
			get
			{
				return this.event3Field;
			}
			set
			{
				this.event3Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event6
		{
			get
			{
				return this.event6Field;
			}
			set
			{
				this.event6Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string zoneEvent
		{
			get
			{
				return this.zoneEventField;
			}
			set
			{
				this.zoneEventField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string zoneEvent2
		{
			get
			{
				return this.zoneEvent2Field;
			}
			set
			{
				this.zoneEvent2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event4
		{
			get
			{
				return this.event4Field;
			}
			set
			{
				this.event4Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event2
		{
			get
			{
				return this.event2Field;
			}
			set
			{
				this.event2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event20
		{
			get
			{
				return this.event20Field;
			}
			set
			{
				this.event20Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event16
		{
			get
			{
				return this.event16Field;
			}
			set
			{
				this.event16Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event24
		{
			get
			{
				return this.event24Field;
			}
			set
			{
				this.event24Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event12
		{
			get
			{
				return this.event12Field;
			}
			set
			{
				this.event12Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event14
		{
			get
			{
				return this.event14Field;
			}
			set
			{
				this.event14Field = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigDeviceStatesDeviceStateLeave
	{

		private string eventField;

		private string event1Field;

		private string zoneEventField;

		private string panelStateField;

		private string event2Field;

		private string event4Field;

		private string event7Field;

		private string event9Field;

		private string event5Field;

		private string zoneEvent1Field;

		private string zoneEvent2Field;

		private string event20Field;

		private string event6Field;

		private string event8Field;

		private string event10Field;

		private string event12Field;

		private string event14Field;

		private string event16Field;

		private string event18Field;

		private string event22Field;

		private string event24Field;

		private string event26Field;

		private string event30Field;

		private string event3Field;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @event
		{
			get
			{
				return this.eventField;
			}
			set
			{
				this.eventField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event1
		{
			get
			{
				return this.event1Field;
			}
			set
			{
				this.event1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string zoneEvent
		{
			get
			{
				return this.zoneEventField;
			}
			set
			{
				this.zoneEventField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string panelState
		{
			get
			{
				return this.panelStateField;
			}
			set
			{
				this.panelStateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event2
		{
			get
			{
				return this.event2Field;
			}
			set
			{
				this.event2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event4
		{
			get
			{
				return this.event4Field;
			}
			set
			{
				this.event4Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event7
		{
			get
			{
				return this.event7Field;
			}
			set
			{
				this.event7Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event9
		{
			get
			{
				return this.event9Field;
			}
			set
			{
				this.event9Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event5
		{
			get
			{
				return this.event5Field;
			}
			set
			{
				this.event5Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string zoneEvent1
		{
			get
			{
				return this.zoneEvent1Field;
			}
			set
			{
				this.zoneEvent1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string zoneEvent2
		{
			get
			{
				return this.zoneEvent2Field;
			}
			set
			{
				this.zoneEvent2Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event20
		{
			get
			{
				return this.event20Field;
			}
			set
			{
				this.event20Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event6
		{
			get
			{
				return this.event6Field;
			}
			set
			{
				this.event6Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event8
		{
			get
			{
				return this.event8Field;
			}
			set
			{
				this.event8Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event10
		{
			get
			{
				return this.event10Field;
			}
			set
			{
				this.event10Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event12
		{
			get
			{
				return this.event12Field;
			}
			set
			{
				this.event12Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event14
		{
			get
			{
				return this.event14Field;
			}
			set
			{
				this.event14Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event16
		{
			get
			{
				return this.event16Field;
			}
			set
			{
				this.event16Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event18
		{
			get
			{
				return this.event18Field;
			}
			set
			{
				this.event18Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event22
		{
			get
			{
				return this.event22Field;
			}
			set
			{
				this.event22Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event24
		{
			get
			{
				return this.event24Field;
			}
			set
			{
				this.event24Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event26
		{
			get
			{
				return this.event26Field;
			}
			set
			{
				this.event26Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event30
		{
			get
			{
				return this.event30Field;
			}
			set
			{
				this.event30Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string event3
		{
			get
			{
				return this.event3Field;
			}
			set
			{
				this.event3Field = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class driverConfigDevicePropInfosDevicePropInfo
	{

		private string tableTypeField;

		private string classField;

		private string nameField;

		private string command1Field;

		private string shiftInMemoryField;

		private string commandDevField;

		private string maskCmdDevField;

		private string captionField;

		private string hintField;

		private string hiddenField;

		private string blockNameField;

		private string imageIndexField;

		private string delayField;

		private string offField;

		private string expectedStateField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string tableType
		{
			get
			{
				return this.tableTypeField;
			}
			set
			{
				this.tableTypeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @class
		{
			get
			{
				return this.classField;
			}
			set
			{
				this.classField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string command1
		{
			get
			{
				return this.command1Field;
			}
			set
			{
				this.command1Field = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string shiftInMemory
		{
			get
			{
				return this.shiftInMemoryField;
			}
			set
			{
				this.shiftInMemoryField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string commandDev
		{
			get
			{
				return this.commandDevField;
			}
			set
			{
				this.commandDevField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string maskCmdDev
		{
			get
			{
				return this.maskCmdDevField;
			}
			set
			{
				this.maskCmdDevField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string caption
		{
			get
			{
				return this.captionField;
			}
			set
			{
				this.captionField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string hint
		{
			get
			{
				return this.hintField;
			}
			set
			{
				this.hintField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string hidden
		{
			get
			{
				return this.hiddenField;
			}
			set
			{
				this.hiddenField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string blockName
		{
			get
			{
				return this.blockNameField;
			}
			set
			{
				this.blockNameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string imageIndex
		{
			get
			{
				return this.imageIndexField;
			}
			set
			{
				this.imageIndexField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string Delay
		{
			get
			{
				return this.delayField;
			}
			set
			{
				this.delayField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string off
		{
			get
			{
				return this.offField;
			}
			set
			{
				this.offField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string expectedState
		{
			get
			{
				return this.expectedStateField;
			}
			set
			{
				this.expectedStateField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class NewDataSet
	{

		private object[] itemsField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("bit", typeof(bit))]
		[System.Xml.Serialization.XmlElementAttribute("driverConfig", typeof(driverConfig))]
		public object[] Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}
}