//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.FireAdministrator.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.FireAdministrator.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept configuration.
        /// </summary>
        public static string AcceptConfig {
            get {
                return ResourceManager.GetString("AcceptConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acception configuration.
        /// </summary>
        public static string AcceptionConfig {
            get {
                return ResourceManager.GetString("AcceptionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administator {
            get {
                return ResourceManager.GetString("Administator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check configuration.
        /// </summary>
        public static string CheckConfig {
            get {
                return ResourceManager.GetString("CheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check user permissions.
        /// </summary>
        public static string CheckUserPermission {
            get {
                return ResourceManager.GetString("CheckUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client settings loading.
        /// </summary>
        public static string ClientSettingsLoad {
            get {
                return ResourceManager.GetString("ClientSettingsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time panel.
        /// </summary>
        public static string ClockPanel {
            get {
                return ResourceManager.GetString("ClockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clocks.
        /// </summary>
        public static string Clocks {
            get {
                return ResourceManager.GetString("Clocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration is contains errors. Continue?.
        /// </summary>
        public static string ConfigWithErrors {
            get {
                return ResourceManager.GetString("ConfigWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content container.
        /// </summary>
        public static string ContainerContent {
            get {
                return ResourceManager.GetString("ContainerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new configuration.
        /// </summary>
        public static string CreateNewConfig {
            get {
                return ResourceManager.GetString("CreateNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open configuration from file.
        /// </summary>
        public static string FileConfigOpen {
            get {
                return ResourceManager.GetString("FileConfigOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration to file.
        /// </summary>
        public static string FileConfigSave {
            get {
                return ResourceManager.GetString("FileConfigSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File synchronisation.
        /// </summary>
        public static string FileSynchronisation {
            get {
                return ResourceManager.GetString("FileSynchronisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules loading.
        /// </summary>
        public static string ModulesLoad {
            get {
                return ResourceManager.GetString("ModulesLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation panel.
        /// </summary>
        public static string NavigationPanel {
            get {
                return ResourceManager.GetString("NavigationPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigator.
        /// </summary>
        public static string Navigator {
            get {
                return ResourceManager.GetString("Navigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no permissions to work with software.
        /// </summary>
        public static string NoWorkPermissions {
            get {
                return ResourceManager.GetString("NoWorkPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading configuration.
        /// </summary>
        public static string ReadingConfig {
            get {
                return ResourceManager.GetString("ReadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report panel.
        /// </summary>
        public static string ReportPanel {
            get {
                return ResourceManager.GetString("ReportPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configuration from the server.
        /// </summary>
        public static string ServerConfigLoad {
            get {
                return ResourceManager.GetString("ServerConfigLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was terminated by server.
        ///Application will be closed..
        /// </summary>
        public static string ServerConnectionRefused {
            get {
                return ResourceManager.GetString("ServerConnectionRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection was terminated by server due the license change.
        ///Apllication will be closed..
        /// </summary>
        public static string ServerConnectionRefused_License {
            get {
                return ResourceManager.GetString("ServerConnectionRefused_License", resourceCulture);
            }
        }
    }
}
