//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RviOperatorClient.RviIntegrationVideoStreamingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RviIntegrationVideoStreamingServiceReference.IIntegrationVideoStreaming")]
    public interface IIntegrationVideoStreaming {
        
        // CODEGEN: Generating message contract since the wrapper name (VideoFileStreamingIn) of message VideoFileStreamingIn does not match the default value (GetVideoFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegrationVideoStreaming/GetVideoFile", ReplyAction="http://tempuri.org/IIntegrationVideoStreaming/GetVideoFileResponse")]
        RviOperatorClient.RviIntegrationVideoStreamingServiceReference.VideoFileStreamingOut GetVideoFile(RviOperatorClient.RviIntegrationVideoStreamingServiceReference.VideoFileStreamingIn request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VideoFileStreamingIn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VideoFileStreamingIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int ChannelNumber;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.Guid DeviceGuid;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.Guid EventGuid;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.Guid Request;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.Guid Session;
        
        public VideoFileStreamingIn() {
        }
        
        public VideoFileStreamingIn(int ChannelNumber, System.Guid DeviceGuid, System.Guid EventGuid, System.Guid Request, System.Guid Session) {
            this.ChannelNumber = ChannelNumber;
            this.DeviceGuid = DeviceGuid;
            this.EventGuid = EventGuid;
            this.Request = Request;
            this.Session = Session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VideoFileStreamingOut", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VideoFileStreamingOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int ErrorCode;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string ErrorInformation;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.Guid Request;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.Guid Session;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileContent;
        
        public VideoFileStreamingOut() {
        }
        
        public VideoFileStreamingOut(int ErrorCode, string ErrorInformation, System.Guid Request, System.Guid Session, System.IO.Stream FileContent) {
            this.ErrorCode = ErrorCode;
            this.ErrorInformation = ErrorInformation;
            this.Request = Request;
            this.Session = Session;
            this.FileContent = FileContent;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegrationVideoStreamingChannel : RviOperatorClient.RviIntegrationVideoStreamingServiceReference.IIntegrationVideoStreaming, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationVideoStreamingClient : System.ServiceModel.ClientBase<RviOperatorClient.RviIntegrationVideoStreamingServiceReference.IIntegrationVideoStreaming>, RviOperatorClient.RviIntegrationVideoStreamingServiceReference.IIntegrationVideoStreaming {
        
        public IntegrationVideoStreamingClient() {
        }
        
        public IntegrationVideoStreamingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationVideoStreamingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationVideoStreamingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationVideoStreamingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RviOperatorClient.RviIntegrationVideoStreamingServiceReference.VideoFileStreamingOut RviOperatorClient.RviIntegrationVideoStreamingServiceReference.IIntegrationVideoStreaming.GetVideoFile(RviOperatorClient.RviIntegrationVideoStreamingServiceReference.VideoFileStreamingIn request) {
            return base.Channel.GetVideoFile(request);
        }
        
        public int GetVideoFile(int ChannelNumber, System.Guid DeviceGuid, System.Guid EventGuid, ref System.Guid Request, ref System.Guid Session, out string ErrorInformation, out System.IO.Stream FileContent) {
            RviOperatorClient.RviIntegrationVideoStreamingServiceReference.VideoFileStreamingIn inValue = new RviOperatorClient.RviIntegrationVideoStreamingServiceReference.VideoFileStreamingIn();
            inValue.ChannelNumber = ChannelNumber;
            inValue.DeviceGuid = DeviceGuid;
            inValue.EventGuid = EventGuid;
            inValue.Request = Request;
            inValue.Session = Session;
            RviOperatorClient.RviIntegrationVideoStreamingServiceReference.VideoFileStreamingOut retVal = ((RviOperatorClient.RviIntegrationVideoStreamingServiceReference.IIntegrationVideoStreaming)(this)).GetVideoFile(inValue);
            ErrorInformation = retVal.ErrorInformation;
            Request = retVal.Request;
            Session = retVal.Session;
            FileContent = retVal.FileContent;
            return retVal.ErrorCode;
        }
    }
}
