//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.IntegrationOPC.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.IntegrationOPC.Errors.CommonErrors", typeof(CommonErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting OPS zone list. Make sure that the integration server is running, and check the network settings..
        /// </summary>
        public static string GetOPCZonesContent_Error {
            get {
                return ResourceManager.GetString("GetOPCZonesContent_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the IP-address can not be empty..
        /// </summary>
        public static string IPAddressEmptyContent_Error {
            get {
                return ResourceManager.GetString("IPAddressEmptyContent_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port value can not be zero..
        /// </summary>
        public static string PortIsZeroContent_Error {
            get {
                return ResourceManager.GetString("PortIsZeroContent_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port value can not be negative..
        /// </summary>
        public static string PortLowerZeroContent_Error {
            get {
                return ResourceManager.GetString("PortLowerZeroContent_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound SFS zone.
        /// </summary>
        public static string UnboundZone_Error {
            get {
                return ResourceManager.GetString("UnboundZone_Error", resourceCulture);
            }
        }
    }
}
