//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyGenerator.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LicenseEntity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LicenseEntity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyGenerator.Resources.Language.LicenseEntity", typeof(LicenseEntity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль &quot;Автоматизация&quot;.
        /// </summary>
        internal static string IsEnabledAutomation {
            get {
                return ResourceManager.GetString("IsEnabledAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль &quot;Фотоверификация&quot;.
        /// </summary>
        internal static string IsEnabledPhotoVerification {
            get {
                return ResourceManager.GetString("IsEnabledPhotoVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль &quot;Интеграция видео RVi&quot;.
        /// </summary>
        internal static string IsEnabledRVI {
            get {
                return ResourceManager.GetString("IsEnabledRVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер A.C. Tech.
        /// </summary>
        internal static string IsEnabledServer {
            get {
                return ResourceManager.GetString("IsEnabledServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль &quot;Учет рабочего времени&quot;.
        /// </summary>
        internal static string IsEnabledURV {
            get {
                return ResourceManager.GetString("IsEnabledURV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия неограниченное количество пользователей.
        /// </summary>
        internal static string IsUnlimitedUsers {
            get {
                return ResourceManager.GetString("IsUnlimitedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оперативная задача (подключение).
        /// </summary>
        internal static string OperatorConnectionsNumber {
            get {
                return ResourceManager.GetString("OperatorConnectionsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего пользователей.
        /// </summary>
        internal static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
    }
}
