using System;
using System.Runtime.Serialization;

namespace FiresecAPI.GK
{
	[DataContract]
	public class GKPim : GKBase
	{
		public override GKBaseObjectType ObjectType { get { return GKBaseObjectType.Pim; } }

		[DataMember]
		public bool IsAutoGenerated { get; set; }

		[DataMember]
		public Guid MPTUID { get; set; }

		[DataMember]
		public Guid PumpStationUID { get; set; }

		public override string PresentationName
		{
			get { return Name; }
		}
	}
}