using System;
using System.Runtime.Serialization;

namespace FiresecAPI.GK
{
	public class XPim : XBase
	{
		public override XBaseObjectType ObjectType { get { return XBaseObjectType.Pim; } }

		public bool IsAutoGenerated { get; set; }
		public Guid MPTUID { get; set; }
		public Guid PumpStationUID { get; set; }

		public override string PresentationName
		{
			get { return Name; }
		}
	}
}