<?xml version="1.0" encoding="utf-8"?><Database Name="Journal_1" Class="JournalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=Journal_1;Integrated Security=True" SettingsObjectName="StrazhDAL.Properties.Settings" SettingsPropertyName="Journal_1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Journal" Member="Journals">
    <Type Name="Journal" Id="ID1">
      <Column Name="UID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SystemDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DeviceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Subsystem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DescriptionText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ObjectType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ObjectName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ObjectUID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Detalisation" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmployeeUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="VideoUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CameraUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ErrorCode" Type="System.Int32" DbType="int" CanBeNull="true" />
      <Column Name="ControllerUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetLastJournalItemProducedByController" Method="GetLastJournalItemProducedByController">
    <Parameter Name="contollerUid" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>