//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiresecAPI.Resources.Language.Models.Automation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcedureStepType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcedureStepType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiresecAPI.Resources.Language.Models.Automation.ProcedureStepType", typeof(ProcedureStepType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить запись в журнал.
        /// </summary>
        internal static string AddJournalItem {
            get {
                return ResourceManager.GetString("AddJournalItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Арифметическая операция.
        /// </summary>
        internal static string Arithmetics {
            get {
                return ResourceManager.GetString("Arithmetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из цикла.
        /// </summary>
        internal static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение списка.
        /// </summary>
        internal static string ChangeList {
            get {
                return ResourceManager.GetString("ChangeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка прав.
        /// </summary>
        internal static string CheckPermission {
            get {
                return ResourceManager.GetString("CheckPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить цикл.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление точкой доступа.
        /// </summary>
        internal static string ControlDoor {
            get {
                return ResourceManager.GetString("ControlDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение свойства элементами плана.
        /// </summary>
        internal static string ControlPlanGet {
            get {
                return ResourceManager.GetString("ControlPlanGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка свойства элементами плана.
        /// </summary>
        internal static string ControlPlanSet {
            get {
                return ResourceManager.GetString("ControlPlanSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление устройством СКД.
        /// </summary>
        internal static string ControlSKDDevice {
            get {
                return ResourceManager.GetString("ControlSKDDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление зоной СКД.
        /// </summary>
        internal static string ControlSKDZone {
            get {
                return ResourceManager.GetString("ControlSKDZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтение свойства визуального элемента.
        /// </summary>
        internal static string ControlVisualGet {
            get {
                return ResourceManager.GetString("ControlVisualGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка свойства визуального элемента.
        /// </summary>
        internal static string ControlVisualSet {
            get {
                return ResourceManager.GetString("ControlVisualSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DoAction {
            get {
                return ResourceManager.GetString("DoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход из процедуры.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт конфигурации.
        /// </summary>
        internal static string ExportConfiguration {
            get {
                return ResourceManager.GetString("ExportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт журнала.
        /// </summary>
        internal static string ExportJournal {
            get {
                return ResourceManager.GetString("ExportJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт организации.
        /// </summary>
        internal static string ExportOrganisation {
            get {
                return ResourceManager.GetString("ExportOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт списка организаций.
        /// </summary>
        internal static string ExportOrganisationList {
            get {
                return ResourceManager.GetString("ExportOrganisationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт отчета.
        /// </summary>
        internal static string ExportReport {
            get {
                return ResourceManager.GetString("ExportReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти объекты.
        /// </summary>
        internal static string FindObjects {
            get {
                return ResourceManager.GetString("FindObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цикл со счетчиком (For).
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цикл по списку.
        /// </summary>
        internal static string Foreach {
            get {
                return ResourceManager.GetString("Foreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тело цикла.
        /// </summary>
        internal static string ForeachBody {
            get {
                return ResourceManager.GetString("ForeachBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генерировать идентификатор.
        /// </summary>
        internal static string GenerateGuid {
            get {
                return ResourceManager.GetString("GenerateGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить текущее время.
        /// </summary>
        internal static string GetDateTimeNow {
            get {
                return ResourceManager.GetString("GetDateTimeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение свойства точки доступа.
        /// </summary>
        internal static string GetDoorProperty {
            get {
                return ResourceManager.GetString("GetDoorProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить значение журнала.
        /// </summary>
        internal static string GetJournalItem {
            get {
                return ResourceManager.GetString("GetJournalItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить размер списка.
        /// </summary>
        internal static string GetListCount {
            get {
                return ResourceManager.GetString("GetListCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить элемент списка.
        /// </summary>
        internal static string GetListItem {
            get {
                return ResourceManager.GetString("GetListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить значение свойства объекта.
        /// </summary>
        internal static string GetObjectProperty {
            get {
                return ResourceManager.GetString("GetObjectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение свойства устройства СКД.
        /// </summary>
        internal static string GetSkdDeviceProperty {
            get {
                return ResourceManager.GetString("GetSkdDeviceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получение свойства зоны СКД.
        /// </summary>
        internal static string GetSkdZoneProperty {
            get {
                return ResourceManager.GetString("GetSkdZoneProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условие.
        /// </summary>
        internal static string If {
            get {
                return ResourceManager.GetString("If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выполняется.
        /// </summary>
        internal static string IfNo {
            get {
                return ResourceManager.GetString("IfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется.
        /// </summary>
        internal static string IfYes {
            get {
                return ResourceManager.GetString("IfYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт организации.
        /// </summary>
        internal static string ImportOrganisation {
            get {
                return ResourceManager.GetString("ImportOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт списка организаций.
        /// </summary>
        internal static string ImportOrganisationList {
            get {
                return ResourceManager.GetString("ImportOrganisationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инкремент значения переменной.
        /// </summary>
        internal static string IncrementValue {
            get {
                return ResourceManager.GetString("IncrementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пауза.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проигрывание звука.
        /// </summary>
        internal static string PlaySound {
            get {
                return ResourceManager.GetString("PlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функция выбора процедуры.
        /// </summary>
        internal static string ProcedureSelection {
            get {
                return ResourceManager.GetString("ProcedureSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление PTZ камерой.
        /// </summary>
        internal static string Ptz {
            get {
                return ResourceManager.GetString("Ptz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайное значение.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск программы.
        /// </summary>
        internal static string RunProgram {
            get {
                return ResourceManager.GetString("RunProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вызвать тревогу в RVI Оператор.
        /// </summary>
        internal static string RviAlarm {
            get {
                return ResourceManager.GetString("RviAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение по электронной почте.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначить идентификатор события.
        /// </summary>
        internal static string SetJournalItemGuid {
            get {
                return ResourceManager.GetString("SetJournalItemGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание значения переменной.
        /// </summary>
        internal static string SetValue {
            get {
                return ResourceManager.GetString("SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать диалоговую форму.
        /// </summary>
        internal static string ShowDialog {
            get {
                return ResourceManager.GetString("ShowDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать сообщение.
        /// </summary>
        internal static string ShowMessage {
            get {
                return ResourceManager.GetString("ShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать свойство объекта.
        /// </summary>
        internal static string ShowProperty {
            get {
                return ResourceManager.GetString("ShowProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать запись.
        /// </summary>
        internal static string StartRecord {
            get {
                return ResourceManager.GetString("StartRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить запись.
        /// </summary>
        internal static string StopRecord {
            get {
                return ResourceManager.GetString("StopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цикл с условием (While).
        /// </summary>
        internal static string While {
            get {
                return ResourceManager.GetString("While", resourceCulture);
            }
        }
    }
}
