//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Strazh.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonViewModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Strazh.ViewModels.CommonViewModels", typeof(CommonViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this you need to apply the configuration. Apply now?.
        /// </summary>
        public static string AcceptConfig {
            get {
                return ResourceManager.GetString("AcceptConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before performing the operation you want to apply the configuration..
        /// </summary>
        public static string AcceptConfigBeforeOperation {
            get {
                return ResourceManager.GetString("AcceptConfigBeforeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actively.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Devices.
        /// </summary>
        public static string AutosearchDevices {
            get {
                return ResourceManager.GetString("AutosearchDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic drawing.
        /// </summary>
        public static string BaseImage {
            get {
                return ResourceManager.GetString("BaseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera Selection.
        /// </summary>
        public static string Camera_Selectation {
            get {
                return ResourceManager.GetString("Camera_Selectation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration controller.
        /// </summary>
        public static string Controller_Config {
            get {
                return ResourceManager.GetString("Controller_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the controller &quot;{0}&quot;.
        /// </summary>
        public static string Controller_DeleteConfirm {
            get {
                return ResourceManager.GetString("Controller_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running the controller restart. The controller will be available within a few seconds.
        /// </summary>
        public static string Controller_Reboot {
            get {
                return ResourceManager.GetString("Controller_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller firmware has been successfully updated.
        /// </summary>
        public static string ControllerFirmwareUpdated {
            get {
                return ResourceManager.GetString("ControllerFirmwareUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network settings are not written to the controller. Change the network settings in the configuration?.
        /// </summary>
        public static string ControllerNetSettings_Save {
            get {
                return ResourceManager.GetString("ControllerNetSettings_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Controller Settings.
        /// </summary>
        public static string ControllerNetSettings_Title {
            get {
                return ResourceManager.GetString("ControllerNetSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty password.
        /// </summary>
        public static string ControllerPasword_EmptyPass {
            get {
                return ResourceManager.GetString("ControllerPasword_EmptyPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller is not login.
        /// </summary>
        public static string ControllerPasword_NoLogin {
            get {
                return ResourceManager.GetString("ControllerPasword_NoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller is no password.
        /// </summary>
        public static string ControllerPasword_NoPass {
            get {
                return ResourceManager.GetString("ControllerPasword_NoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string ControllerPasword_PassNotConfirm {
            get {
                return ResourceManager.GetString("ControllerPasword_PassNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed in the controller. Change your password in the configuration?.
        /// </summary>
        public static string ControllerPasword_Save {
            get {
                return ResourceManager.GetString("ControllerPasword_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Setting a password.
        /// </summary>
        public static string ControllerPasword_Title {
            get {
                return ResourceManager.GetString("ControllerPasword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during time synchronization operation.
        /// </summary>
        public static string ControllerTimeSettings_SynchError {
            get {
                return ResourceManager.GetString("ControllerTimeSettings_SynchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time synchronization operation was successful.
        /// </summary>
        public static string ControllerTimeSettings_SynchSuccess {
            get {
                return ResourceManager.GetString("ControllerTimeSettings_SynchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the daily chart of access &quot;{0}&quot;?.
        /// </summary>
        public static string DayAccessSchedule_DeleteConfirm {
            get {
                return ResourceManager.GetString("DayAccessSchedule_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The daily chart of access &quot;{0}&quot; is used in one or more of the weekly charts of access. When it is removed it will be replaced in the weekly charts of access to the daily chart of &quot;Never.&quot; Are you sure you want to remove it?.
        /// </summary>
        public static string DayAccessSchedule_DeleteForWeekConfirm {
            get {
                return ResourceManager.GetString("DayAccessSchedule_DeleteForWeekConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the daily chart of the castle &quot;{0}&quot;?.
        /// </summary>
        public static string DayLockSchedule_DeleteConfirm {
            get {
                return ResourceManager.GetString("DayLockSchedule_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily schedule of the castle &quot;{0}&quot; is used in one or more of the weekly chart of the castle. When it is removed it will be replaced in the weekly charts of the castle on the daily chart of the &quot;Map&quot;. Are you sure you want to remove it?.
        /// </summary>
        public static string DayLockSchedule_DeleteForWeekConfirm {
            get {
                return ResourceManager.GetString("DayLockSchedule_DeleteForWeekConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full schedule of the castle with the same name already exists.
        /// </summary>
        public static string DayLockSchedule_Exist {
            get {
                return ResourceManager.GetString("DayLockSchedule_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new daytime schedule.
        /// </summary>
        public static string DaySchedule_Creation {
            get {
                return ResourceManager.GetString("DaySchedule_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties day schedules: {0}.
        /// </summary>
        public static string DaySchedule_Properties {
            get {
                return ResourceManager.GetString("DaySchedule_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the device.
        /// </summary>
        public static string Device_Select {
            get {
                return ResourceManager.GetString("Device_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Device.
        /// </summary>
        public static string Device_Selectation {
            get {
                return ResourceManager.GetString("Device_Selectation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recording process permits all controllers may take a few minutes. During this time, the application will not be available. Continue?.
        /// </summary>
        public static string Device_WriteCardsOnController {
            get {
                return ResourceManager.GetString("Device_WriteCardsOnController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to controller Options.
        /// </summary>
        public static string Devices_ControllerParams {
            get {
                return ResourceManager.GetString("Devices_ControllerParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to door Options.
        /// </summary>
        public static string Devices_DoorParams {
            get {
                return ResourceManager.GetString("Devices_DoorParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an access point.
        /// </summary>
        public static string Door_Creation {
            get {
                return ResourceManager.GetString("Door_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the access point &quot;{0}&quot;?.
        /// </summary>
        public static string Door_DeleteConfirm {
            get {
                return ResourceManager.GetString("Door_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access point with this number already exists.
        /// </summary>
        public static string Door_Exist {
            get {
                return ResourceManager.GetString("Door_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties AP: {0}.
        /// </summary>
        public static string Door_Properties {
            get {
                return ResourceManager.GetString("Door_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to figures Properties: Device SKD.
        /// </summary>
        public static string FigureProperties_SKDDevice {
            get {
                return ResourceManager.GetString("FigureProperties_SKDDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to figures Properties: AP.
        /// </summary>
        public static string FigureProperties_SKDDoor {
            get {
                return ResourceManager.GetString("FigureProperties_SKDDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to figures Properties Zone SKD.
        /// </summary>
        public static string FigureProperties_SKDZone {
            get {
                return ResourceManager.GetString("FigureProperties_SKDZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forbidden name.
        /// </summary>
        public static string ForbiddenName {
            get {
                return ResourceManager.GetString("ForbiddenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit public holiday.
        /// </summary>
        public static string Holiday_Edition {
            get {
                return ResourceManager.GetString("Holiday_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not active.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting interval.
        /// </summary>
        public static string Interval_Creation {
            get {
                return ResourceManager.GetString("Interval_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To lock the controller is not established a method of opening the door.
        /// </summary>
        public static string Lock_EmptyOpenMethod {
            get {
                return ResourceManager.GetString("Lock_EmptyOpenMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle schedule is not selected.
        /// </summary>
        public static string LockSchedule_NotSelect {
            get {
                return ResourceManager.GetString("LockSchedule_NotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new daytime schedule.
        /// </summary>
        public static string NewDaySchedule {
            get {
                return ResourceManager.GetString("NewDaySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new device.
        /// </summary>
        public static string NewDevice {
            get {
                return ResourceManager.GetString("NewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Access Point.
        /// </summary>
        public static string NewDoor {
            get {
                return ResourceManager.GetString("NewDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New holiday.
        /// </summary>
        public static string NewHoliday {
            get {
                return ResourceManager.GetString("NewHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new zone.
        /// </summary>
        public static string NewZone {
            get {
                return ResourceManager.GetString("NewZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be a positive number.
        /// </summary>
        public static string NumberIsPositive {
            get {
                return ResourceManager.GetString("NumberIsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unilateral.
        /// </summary>
        public static string OneWay {
            get {
                return ResourceManager.GetString("OneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors found. Operation aborted.
        /// </summary>
        public static string Operation_Error {
            get {
                return ResourceManager.GetString("Operation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed successfully.
        /// </summary>
        public static string Operation_Success {
            get {
                return ResourceManager.GetString("Operation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties reader {0}.
        /// </summary>
        public static string Reader_Properties {
            get {
                return ResourceManager.GetString("Reader_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reset all parameters of the controller will be installed at the factory, and the recorded passes will be erased. Continue?.
        /// </summary>
        public static string ResetConfig {
            get {
                return ResourceManager.GetString("ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding posutochny schedule {0}.
        /// </summary>
        public static string SlideDaySchedule {
            get {
                return ResourceManager.GetString("SlideDaySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing sliding Daily schedule.
        /// </summary>
        public static string SlideDaySchedule_Edition {
            get {
                return ResourceManager.GetString("SlideDaySchedule_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliding The weekly schedule {0}.
        /// </summary>
        public static string SlideWeekSchedule {
            get {
                return ResourceManager.GetString("SlideWeekSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing sliding Weekly schedule.
        /// </summary>
        public static string SlideWeekSchedule_Edition {
            get {
                return ResourceManager.GetString("SlideWeekSchedule_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double-sided.
        /// </summary>
        public static string TwoWay {
            get {
                return ResourceManager.GetString("TwoWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownDay {
            get {
                return ResourceManager.GetString("UnknownDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Device.
        /// </summary>
        public static string UnknownDevice {
            get {
                return ResourceManager.GetString("UnknownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You installed an older version of the software on the controller. This controller will be in the &quot;Failure&quot;.
        /// </summary>
        public static string UpdateToObsoleteFirmware {
            get {
                return ResourceManager.GetString("UpdateToObsoleteFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verification.
        /// </summary>
        public static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting verification.
        /// </summary>
        public static string Verification_Settings {
            get {
                return ResourceManager.GetString("Verification_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly access &quot;{0}&quot; can be used to determine the criteria for temporary passage through the access point for the already issued permits. When it is removed, he will be replaced by the passage of a criterion corresponding weekly access schedule to &quot;Never&quot;. Are you sure you want to remove it?.
        /// </summary>
        public static string WeekAccessSchedule_DeleteConfirm {
            get {
                return ResourceManager.GetString("WeekAccessSchedule_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the weekly chart of the castle &quot;{0}&quot;?.
        /// </summary>
        public static string WeekLockSchedule_DeleteConfirm {
            get {
                return ResourceManager.GetString("WeekLockSchedule_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly castle &quot;{0}&quot; is assigned to one or more locks. At its removal weekly chart of the castle will be assigned to the castle, &quot;Map&quot;. Are you sure you want to remove it?.
        /// </summary>
        public static string WeekLockSchedule_DeleteForLocksConfirm {
            get {
                return ResourceManager.GetString("WeekLockSchedule_DeleteForLocksConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weekly schedule {0}.
        /// </summary>
        public static string WeekSchedule {
            get {
                return ResourceManager.GetString("WeekSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit weekly schedule.
        /// </summary>
        public static string WeekSchedule_Edition {
            get {
                return ResourceManager.GetString("WeekSchedule_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new zone.
        /// </summary>
        public static string Zone_Creation {
            get {
                return ResourceManager.GetString("Zone_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the zone, &quot;{0}&quot;?.
        /// </summary>
        public static string Zone_DeleteConfirm {
            get {
                return ResourceManager.GetString("Zone_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone with this number already exists.
        /// </summary>
        public static string Zone_Exist {
            get {
                return ResourceManager.GetString("Zone_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zone Properties: {0}.
        /// </summary>
        public static string Zone_Properties {
            get {
                return ResourceManager.GetString("Zone_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the zones.
        /// </summary>
        public static string Zone_Select {
            get {
                return ResourceManager.GetString("Zone_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting a Zone.
        /// </summary>
        public static string Zone_Selectation {
            get {
                return ResourceManager.GetString("Zone_Selectation", resourceCulture);
            }
        }
    }
}
