//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Reports.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonViews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Reports.Views.CommonViews", typeof(CommonViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the height of the page.
        /// </summary>
        public static string AtHeightOfPage {
            get {
                return ResourceManager.GetString("AtHeightOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the width of the page.
        /// </summary>
        public static string AtWidthOfPage {
            get {
                return ResourceManager.GetString("AtWidthOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative calculation of the balance:.
        /// </summary>
        public static string BalanceCalculate {
            get {
                return ResourceManager.GetString("BalanceCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the scale.
        /// </summary>
        public static string ChangeScale {
            get {
                return ResourceManager.GetString("ChangeScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider only overtime (according to the documents processed).
        /// </summary>
        public static string ConsiderOvertimeWithDoc {
            get {
                return ResourceManager.GetString("ConsiderOvertimeWithDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider overtime, not confirmed by documents.
        /// </summary>
        public static string ConsiderOvertimeWithoutDoc {
            get {
                return ResourceManager.GetString("ConsiderOvertimeWithoutDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.mm.yyyy.
        /// </summary>
        public static string DateMask {
            get {
                return ResourceManager.GetString("DateMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string DecreaseScale {
            get {
                return ResourceManager.GetString("DecreaseScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export document.
        /// </summary>
        public static string DocumentExport {
            get {
                return ResourceManager.GetString("DocumentExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string ExportToCSV {
            get {
                return ResourceManager.GetString("ExportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export in HTM.
        /// </summary>
        public static string ExportToHTM {
            get {
                return ResourceManager.GetString("ExportToHTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to MHT.
        /// </summary>
        public static string ExportToMHT {
            get {
                return ResourceManager.GetString("ExportToMHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        public static string ExportToPDF {
            get {
                return ResourceManager.GetString("ExportToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as RTF.
        /// </summary>
        public static string ExportToRTF {
            get {
                return ResourceManager.GetString("ExportToRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to TXT.
        /// </summary>
        public static string ExportToTXT {
            get {
                return ResourceManager.GetString("ExportToTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XLS.
        /// </summary>
        public static string ExportToXLS {
            get {
                return ResourceManager.GetString("ExportToXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XLSX.
        /// </summary>
        public static string ExportToXLSX {
            get {
                return ResourceManager.GetString("ExportToXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XPS.
        /// </summary>
        public static string ExportToXPS {
            get {
                return ResourceManager.GetString("ExportToXPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Filter2 {
            get {
                return ResourceManager.GetString("Filter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The period of formation.
        /// </summary>
        public static string FormationPeriod {
            get {
                return ResourceManager.GetString("FormationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the report view settings.
        /// </summary>
        public static string HideReportViewSettings {
            get {
                return ResourceManager.GetString("HideReportViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string IncreaseScale {
            get {
                return ResourceManager.GetString("IncreaseScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial size.
        /// </summary>
        public static string InitialSize {
            get {
                return ResourceManager.GetString("InitialSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print report.
        /// </summary>
        public static string PrintReport {
            get {
                return ResourceManager.GetString("PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh report.
        /// </summary>
        public static string RefreshReport {
            get {
                return ResourceManager.GetString("RefreshReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Report in PDF.
        /// </summary>
        public static string SaveInPDF {
            get {
                return ResourceManager.GetString("SaveInPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set filter.
        /// </summary>
        public static string SetUpFilter {
            get {
                return ResourceManager.GetString("SetUpFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display archive information.
        /// </summary>
        public static string ShowArchiveInfo {
            get {
                return ResourceManager.GetString("ShowArchiveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show filter name.
        /// </summary>
        public static string ShowFilterName {
            get {
                return ResourceManager.GetString("ShowFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show filter name in the title.
        /// </summary>
        public static string ShowFilterNameInTitle {
            get {
                return ResourceManager.GetString("ShowFilterNameInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the date and time of the report.
        /// </summary>
        public static string ShowFormationDate {
            get {
                return ResourceManager.GetString("ShowFormationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display formation period of the report.
        /// </summary>
        public static string ShowFormationPeriod {
            get {
                return ResourceManager.GetString("ShowFormationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the report view settings.
        /// </summary>
        public static string ShowReportViewSettings {
            get {
                return ResourceManager.GetString("ShowReportViewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display information about the user, who has been generated report.
        /// </summary>
        public static string ShowUserInfo {
            get {
                return ResourceManager.GetString("ShowUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start page.
        /// </summary>
        public static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
    }
}
