//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Automation.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonViewModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Automation.ViewModels.CommonViewModels", typeof(CommonViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add argument.
        /// </summary>
        public static string Argument_Add {
            get {
                return ResourceManager.GetString("Argument_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit argument.
        /// </summary>
        public static string Argument_Edit {
            get {
                return ResourceManager.GetString("Argument_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to argument.
        /// </summary>
        public static string Argument_Title {
            get {
                return ResourceManager.GetString("Argument_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit argument.
        /// </summary>
        public static string ArgumentDetailsViewModel_Title {
            get {
                return ResourceManager.GetString("ArgumentDetailsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting a video device.
        /// </summary>
        public static string CameraSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("CameraSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the access point.
        /// </summary>
        public static string DoorSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("DoorSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection of personnel.
        /// </summary>
        public static string EmployeeSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("EmployeeSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection filter.
        /// </summary>
        public static string FilterSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("FilterSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a global variable.
        /// </summary>
        public static string GlobalVariable_Add {
            get {
                return ResourceManager.GetString("GlobalVariable_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global variable.
        /// </summary>
        public static string GlobalVariable_DefaultName {
            get {
                return ResourceManager.GetString("GlobalVariable_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the global variable.
        /// </summary>
        public static string GlobalVariable_Edit {
            get {
                return ResourceManager.GetString("GlobalVariable_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the center.
        /// </summary>
        public static string LayoutPartPropertyProcedure_Center {
            get {
                return ResourceManager.GetString("LayoutPartPropertyProcedure_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the left side.
        /// </summary>
        public static string LayoutPartPropertyProcedure_Left {
            get {
                return ResourceManager.GetString("LayoutPartPropertyProcedure_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right.
        /// </summary>
        public static string LayoutPartPropertyProcedure_Right {
            get {
                return ResourceManager.GetString("LayoutPartPropertyProcedure_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a local variable.
        /// </summary>
        public static string LocalVariable_Add {
            get {
                return ResourceManager.GetString("LocalVariable_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local variable.
        /// </summary>
        public static string LocalVariable_DefaultName {
            get {
                return ResourceManager.GetString("LocalVariable_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a local variable.
        /// </summary>
        public static string LocalVariable_Edit {
            get {
                return ResourceManager.GetString("LocalVariable_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection of.
        /// </summary>
        public static string OrganisationSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("OrganisationSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select the Script.
        /// </summary>
        public static string PressToSelectOPCScenarioLabel {
            get {
                return ResourceManager.GetString("PressToSelectOPCScenarioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create procedures.
        /// </summary>
        public static string ProcedureDetails_Create {
            get {
                return ResourceManager.GetString("ProcedureDetails_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing procedures.
        /// </summary>
        public static string ProcedureDetails_Edit {
            get {
                return ResourceManager.GetString("ProcedureDetails_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to figures Properties: Procedure.
        /// </summary>
        public static string ProcedurePropertiesViewModel_Title {
            get {
                return ResourceManager.GetString("ProcedurePropertiesViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Procedures_Add {
            get {
                return ResourceManager.GetString("Procedures_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Procedures_Copy {
            get {
                return ResourceManager.GetString("Procedures_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Procedures_Cut {
            get {
                return ResourceManager.GetString("Procedures_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Procedures_Delete {
            get {
                return ResourceManager.GetString("Procedures_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Procedures_Edit {
            get {
                return ResourceManager.GetString("Procedures_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Procedures_Edition {
            get {
                return ResourceManager.GetString("Procedures_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert.
        /// </summary>
        public static string Procedures_Paste {
            get {
                return ResourceManager.GetString("Procedures_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice of procedure.
        /// </summary>
        public static string ProcedureSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("ProcedureSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario number: {0} Name: {1}.
        /// </summary>
        public static string ScenarioInfoLabel {
            get {
                return ResourceManager.GetString("ScenarioInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a schedule item.
        /// </summary>
        public static string ScheduleDetails_Add {
            get {
                return ResourceManager.GetString("ScheduleDetails_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties schedules element.
        /// </summary>
        public static string ScheduleDetails_Properties {
            get {
                return ResourceManager.GetString("ScheduleDetails_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device.
        /// </summary>
        public static string SKDDeviceSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("SKDDeviceSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting a zone.
        /// </summary>
        public static string SKDZoneSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("SKDZoneSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties of sound element.
        /// </summary>
        public static string SoundDetailsViewModel_Title {
            get {
                return ResourceManager.GetString("SoundDetailsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file | * .wav.
        /// </summary>
        public static string SoundsViewModel_Extention {
            get {
                return ResourceManager.GetString("SoundsViewModel_Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cycle Options.
        /// </summary>
        public static string StepTypeSelection_CycleFunctions {
            get {
                return ResourceManager.GetString("StepTypeSelection_CycleFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exchange.
        /// </summary>
        public static string StepTypeSelection_DataExchange {
            get {
                return ResourceManager.GetString("StepTypeSelection_DataExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register functions.
        /// </summary>
        public static string StepTypeSelection_FunctionsRegister {
            get {
                return ResourceManager.GetString("StepTypeSelection_FunctionsRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facility management.
        /// </summary>
        public static string StepTypeSelection_HardwareControl {
            get {
                return ResourceManager.GetString("StepTypeSelection_HardwareControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive logic.
        /// </summary>
        public static string StepTypeSelection_Logic {
            get {
                return ResourceManager.GetString("StepTypeSelection_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration with OPS.
        /// </summary>
        public static string StepTypeSelection_OPCIntegration {
            get {
                return ResourceManager.GetString("StepTypeSelection_OPCIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operations.
        /// </summary>
        public static string StepTypeSelection_Operations {
            get {
                return ResourceManager.GetString("StepTypeSelection_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service functions.
        /// </summary>
        public static string StepTypeSelection_ServiceFunctions {
            get {
                return ResourceManager.GetString("StepTypeSelection_ServiceFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel Management.
        /// </summary>
        public static string StepTypeSelection_StrazhControl {
            get {
                return ResourceManager.GetString("StepTypeSelection_StrazhControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of function.
        /// </summary>
        public static string StepTypeSelection_Title {
            get {
                return ResourceManager.GetString("StepTypeSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Management.
        /// </summary>
        public static string StepTypeSelection_VideoControl {
            get {
                return ResourceManager.GetString("StepTypeSelection_VideoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line editor.
        /// </summary>
        public static string StringDetailsViewModel_Title {
            get {
                return ResourceManager.GetString("StringDetailsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        public static string UserSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("UserSelectionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing visitor.
        /// </summary>
        public static string VisitorSelectionViewModel_Title {
            get {
                return ResourceManager.GetString("VisitorSelectionViewModel_Title", resourceCulture);
            }
        }
    }
}
