//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaSKDDriver.Resources.Language.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Card {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Card() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChinaSKDDriver.Resources.Language.API.Card", typeof(Card).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задолженность.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_STATE_ARREARAGE {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_STATE_ARREARAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заморожена.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_STATE_FREEZE {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_STATE_FREEZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_STATE_LOGOFF {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_STATE_LOGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потеряна.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_STATE_LOSE {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_STATE_LOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормальное.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_STATE_NORMAL {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_STATE_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просрочка.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_STATE_OVERDUE {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_STATE_OVERDUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не известно.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_STATE_UNKNOWN {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_STATE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокирована.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_TYPE_BLACKLIST {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_TYPE_BLACKLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принуждение.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_TYPE_CORCE {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_TYPE_CORCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обычная.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_TYPE_GENERAL {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_TYPE_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гостевая.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_TYPE_GUEST {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_TYPE_GUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервисная.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_TYPE_MOTHERCARD {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_TYPE_MOTHERCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Патруль.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_TYPE_PATROL {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_TYPE_PATROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не известно.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_TYPE_UNKNOWN {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_TYPE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вип.
        /// </summary>
        internal static string NET_ACCESSCTLCARD_TYPE_VIP {
            get {
                return ResourceManager.GetString("NET_ACCESSCTLCARD_TYPE_VIP", resourceCulture);
            }
        }
    }
}
