//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Strazh.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Strazh.Errors.CommonErrors", typeof(CommonErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock password must meet the following restrictions: 
        ///* Can not be empty 
        ///* Can contain only digits
        ///* Number of digits from 3 to 6
        ///DeviceCommands_ControllerError	
        ///* Must not begin at 0 
        ///* Do not have to match the existing password .
        /// </summary>
        public static string ControllerPassword_Error {
            get {
                return ResourceManager.GetString("ControllerPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was not performed on these controllers: 
        ///{0}.
        /// </summary>
        public static string DeviceCommands_ControllerError {
            get {
                return ResourceManager.GetString("DeviceCommands_ControllerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not true is the default gateway.
        /// </summary>
        public static string GatewayError {
            get {
                return ResourceManager.GetString("GatewayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not true given IP-address.
        /// </summary>
        public static string IPAddressError {
            get {
                return ResourceManager.GetString("IPAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subnet mask is not defined correctly.
        /// </summary>
        public static string MaskError {
            get {
                return ResourceManager.GetString("MaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during operation.
        /// </summary>
        public static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrelated AP.
        /// </summary>
        public static string UnrelatedDoorError {
            get {
                return ResourceManager.GetString("UnrelatedDoorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound access control device.
        /// </summary>
        public static string UnrelatedSKDDeviceError {
            get {
                return ResourceManager.GetString("UnrelatedSKDDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrelated SKD zone.
        /// </summary>
        public static string UnrelatedSKDZoneError {
            get {
                return ResourceManager.GetString("UnrelatedSKDZoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive participates reader at the access point.
        /// </summary>
        public static string ValidateDevices_DoorError {
            get {
                return ResourceManager.GetString("ValidateDevices_DoorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reader is not involved in the access point.
        /// </summary>
        public static string ValidateDevices_DoorNullError {
            get {
                return ResourceManager.GetString("ValidateDevices_DoorNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device name.
        /// </summary>
        public static string ValidateDevices_EmptyNameError {
            get {
                return ResourceManager.GetString("ValidateDevices_EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive reader is in zone.
        /// </summary>
        public static string ValidateDevices_ZoneError {
            get {
                return ResourceManager.GetString("ValidateDevices_ZoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reader does not lead to a zone.
        /// </summary>
        public static string ValidateDevices_ZoneNullError {
            get {
                return ResourceManager.GetString("ValidateDevices_ZoneNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated device name.
        /// </summary>
        public static string ValidateDevicesEqualityicate_DublicateError {
            get {
                return ResourceManager.GetString("ValidateDevicesEqualityicate_DublicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type controller does not match the access point.
        /// </summary>
        public static string ValidateDoors_DeviceTypeError {
            get {
                return ResourceManager.GetString("ValidateDoors_DeviceTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles the access point name.
        /// </summary>
        public static string ValidateDoors_DublicateNameError {
            get {
                return ResourceManager.GetString("ValidateDoors_DublicateNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles room.
        /// </summary>
        public static string ValidateDoors_DublicateNumberError {
            get {
                return ResourceManager.GetString("ValidateDoors_DublicateNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Access Point Name.
        /// </summary>
        public static string ValidateDoors_EmptyNameError {
            get {
                return ResourceManager.GetString("ValidateDoors_EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no access point input device.
        /// </summary>
        public static string ValidateDoors_InDeviceError {
            get {
                return ResourceManager.GetString("ValidateDoors_InDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the access point is not the output device.
        /// </summary>
        public static string ValidateDoors_OutDeviceEmptyError {
            get {
                return ResourceManager.GetString("ValidateDoors_OutDeviceEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the AP incorrectly specified output device.
        /// </summary>
        public static string ValidateDoors_OutDeviceError {
            get {
                return ResourceManager.GetString("ValidateDoors_OutDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At access point output device reader can only be.
        /// </summary>
        public static string ValidateDoors_OutReaderError {
            get {
                return ResourceManager.GetString("ValidateDoors_OutReaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One and the same unit linked to different access points.
        /// </summary>
        public static string ValidateDoors_SameDeviceError {
            get {
                return ResourceManager.GetString("ValidateDoors_SameDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles title on the daily chart.
        /// </summary>
        public static string ValidateDoorTimeIntervals_DublicateError {
            get {
                return ResourceManager.GetString("ValidateDoorTimeIntervals_DublicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles title on the weekly chart.
        /// </summary>
        public static string ValidateDoorWeeklyIntervals_DublicateError {
            get {
                return ResourceManager.GetString("ValidateDoorWeeklyIntervals_DublicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All components of the weekly chart empty.
        /// </summary>
        public static string ValidateDoorWeeklyIntervals_EmptyError {
            get {
                return ResourceManager.GetString("ValidateDoorWeeklyIntervals_EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles holiday date.
        /// </summary>
        public static string ValidateHolidays_DublicateError {
            get {
                return ResourceManager.GetString("ValidateHolidays_DublicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name of the holiday.
        /// </summary>
        public static string ValidateHolidays_EmptyNameError {
            get {
                return ResourceManager.GetString("ValidateHolidays_EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name on the daily chart.
        /// </summary>
        public static string ValidateIntervals_EmptyNameError {
            get {
                return ResourceManager.GetString("ValidateIntervals_EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start interval is less than the end of the interval.
        /// </summary>
        public static string ValidateIntervals_StartLessEndError {
            get {
                return ResourceManager.GetString("ValidateIntervals_StartLessEndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated IP-address of the device.
        /// </summary>
        public static string ValidateIPAddresses_DublicateError {
            get {
                return ResourceManager.GetString("ValidateIPAddresses_DublicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login Not specified.
        /// </summary>
        public static string ValidateIPAddresses_LoginError {
            get {
                return ResourceManager.GetString("ValidateIPAddresses_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password is set.
        /// </summary>
        public static string ValidateIPAddresses_PasswordError {
            get {
                return ResourceManager.GetString("ValidateIPAddresses_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It does not specify a port.
        /// </summary>
        public static string ValidateIPAddresses_PortError {
            get {
                return ResourceManager.GetString("ValidateIPAddresses_PortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is duplicated on the plane {1}.
        /// </summary>
        public static string ValidatePlans_DublicateError {
            get {
                return ResourceManager.GetString("ValidatePlans_DublicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles title sliding Daily schedule.
        /// </summary>
        public static string ValidateSlideDayIntervals_DublicateError {
            get {
                return ResourceManager.GetString("ValidateSlideDayIntervals_DublicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All components of sliding Daily schedule empty.
        /// </summary>
        public static string ValidateSlideDayIntervals_EmptyError {
            get {
                return ResourceManager.GetString("ValidateSlideDayIntervals_EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name sliding Daily schedule.
        /// </summary>
        public static string ValidateSlideDayIntervals_EmptyNameError {
            get {
                return ResourceManager.GetString("ValidateSlideDayIntervals_EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the components of the sliding Daily schedule.
        /// </summary>
        public static string ValidateSlideDayIntervals_EmptyPartError {
            get {
                return ResourceManager.GetString("ValidateSlideDayIntervals_EmptyPartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name sliding Weekly schedule.
        /// </summary>
        public static string ValidateSlideWeeklyIntervals_EmptyNameError {
            get {
                return ResourceManager.GetString("ValidateSlideWeeklyIntervals_EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles title sliding Weekly schedule.
        /// </summary>
        public static string ValidateSlideWeklyIntervals_DublicateError {
            get {
                return ResourceManager.GetString("ValidateSlideWeklyIntervals_DublicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All components of sliding weekly schedule empty.
        /// </summary>
        public static string ValidateSlideWeklyIntervals_EmptyError {
            get {
                return ResourceManager.GetString("ValidateSlideWeklyIntervals_EmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the components sliding on a weekly schedule.
        /// </summary>
        public static string ValidateSlideWeklyIntervals_EmptyPartError {
            get {
                return ResourceManager.GetString("ValidateSlideWeklyIntervals_EmptyPartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the components of the daily chart.
        /// </summary>
        public static string ValidateTimeIntervals_EmptyPartError {
            get {
                return ResourceManager.GetString("ValidateTimeIntervals_EmptyPartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence of intervals must not be intersecting.
        /// </summary>
        public static string ValidateTimeIntervals_IntersectError {
            get {
                return ResourceManager.GetString("ValidateTimeIntervals_IntersectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name on the weekly chart.
        /// </summary>
        public static string ValidateWeeklyIntervals_EmptyNameError {
            get {
                return ResourceManager.GetString("ValidateWeeklyIntervals_EmptyNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubles zone name.
        /// </summary>
        public static string ValidateZones_DublicateError {
            get {
                return ResourceManager.GetString("ValidateZones_DublicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name Zone.
        /// </summary>
        public static string ValidateZones_EmptyNameError {
            get {
                return ResourceManager.GetString("ValidateZones_EmptyNameError", resourceCulture);
            }
        }
    }
}
