<?xml version="1.0" encoding="utf-8"?><Database Name="Firesec" Class="FiresecDbConverterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\sqlexpress;Initial Catalog=Firesec;Integrated Security=True" SettingsObjectName="FiresecService.Properties.Settings" SettingsPropertyName="FiresecConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Journal" Member="Journal">
    <Type Name="Journal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeviceTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SystemTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZoneName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DeviceName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PanelName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DeviceDatabaseId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PanelDatabaseId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StateType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OldId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>