<?xml version="1.0" encoding="utf-8"?><Database Name="Firesec" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Journal" Member="JournalCEs">
    <Type Name="JournalCE">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeviceTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SystemTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ZoneName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DeviceName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="PanelName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DeviceDatabaseId" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="PanelDatabaseId" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="StateType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubSystemType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Detalization" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>