using System.ComponentModel;

namespace FiresecAPI.SKD
{
	public enum Country
	{
		[Description("Аргентина")]
		Argentina,
		[Description("Армения")]
		Armenia,
		[Description("Австралия")]
		Australia,
		[Description("Азербайджан")]
		Azerbaijan,
		[Description("Белоруссия")]
		Belarus,
		[Description("Бразилия")]
		Brazil,
		[Description("Канада")]
		Canada,
		[Description("Китай")]
		China,
		[Description("Эстония")]
		Estonia,
		[Description("Франция")]
		France,
		[Description("Грузия")]
		Georgia,
		[Description("Германия")]
		Germany,
		[Description("Индия")]
		India,
		[Description("Индонезия")]
		Indonesia,
		[Description("Италия")]
		Italy,
		[Description("Япония")]
		Japan,
		[Description("Казахстан")]
		Kazakhstan,
		[Description("Киргизия")]
		Kyrgyzstan,
		[Description("Латвия")]
		Latvia,
		[Description("Литва")]
		Lithuania,
		[Description("Мексика")]
		Mexico,
		[Description("Молдавия")]
		Moldova,
		[Description("Россия")]
		Russia,
		[Description("Саудовская Аравия")]
		SaudiArabia,
		[Description("ЮАР")]
		SouthAfrica,
		[Description("Южная Корея")]
		SouthKorea,
		[Description("Таджикистан")]
		Tajikistan,
		[Description("Туркменистан")]
		Turkmenistan,
		[Description("Украина")]
		Ukraine,
		[Description("Великобритания")]
		UnitedKingdom,
		[Description("США")]
		UnitedStates,
		[Description("Узбекистан")]
		Uzbekistan
	}
}