using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace FiresecAPI.GK
{
	[DataContract]
	public class GKDelay : GKBase
	{
		public GKDelay()
		{
			DeviceLogic = new GKDeviceLogic();
		}

		[DataMember]
		public ushort DelayTime { get; set; }

		[DataMember]
		public ushort Hold { get; set; }

		[DataMember]
		public DelayRegime DelayRegime { get; set; }

		[DataMember]
		public GKDeviceLogic DeviceLogic { get; set; }

		[DataMember]
		public bool IsAutoGenerated { get; set; }

		[DataMember]
		public Guid PumpStationUID { get; set; }

		[XmlIgnore]
		public override GKBaseObjectType ObjectType { get { return GKBaseObjectType.Delay; } }

		[XmlIgnore]
		public override string PresentationName
		{
			get { return Name; }
		}
	}
}