using System;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace FiresecAPI.GK
{
	[DataContract]
	public class XDelay : XBase
	{
		public XDelay()
		{
			DeviceLogic = new XDeviceLogic();
		}

		[DataMember]
		public ushort DelayTime { get; set; }

		[DataMember]
		public ushort Hold { get; set; }

		[DataMember]
		public DelayRegime DelayRegime { get; set; }

		[DataMember]
		public XDeviceLogic DeviceLogic { get; set; }

		[DataMember]
		public bool IsAutoGenerated { get; set; }

		[DataMember]
		public Guid PumpStationUID { get; set; }

		[XmlIgnore]
		public override XBaseObjectType ObjectType { get { return XBaseObjectType.Delay; } }

		[XmlIgnore]
		public override string PresentationName
		{
			get { return Name; }
		}
	}
}