//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiresecService.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiresecService.Resources.Language.MainView", typeof(MainView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить лицензию.
        /// </summary>
        public static string Button_LoadLicense {
            get {
                return ResourceManager.GetString("Button_LoadLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разорвать соединение.
        /// </summary>
        public static string Button_ReleaseConnection {
            get {
                return ResourceManager.GetString("Button_ReleaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string DataGridTemplateColumn_Identifier {
            get {
                return ResourceManager.GetString("DataGridTemplateColumn_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string DataGridTextColumn_Address {
            get {
                return ResourceManager.GetString("DataGridTextColumn_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string DataGridTextColumn_Type {
            get {
                return ResourceManager.GetString("DataGridTextColumn_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string DataGridTextColumn_User {
            get {
                return ResourceManager.GetString("DataGridTextColumn_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединения.
        /// </summary>
        public static string TabItem_Connections {
            get {
                return ResourceManager.GetString("TabItem_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензирование.
        /// </summary>
        public static string TabItem_License {
            get {
                return ResourceManager.GetString("TabItem_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        public static string TabItem_Log {
            get {
                return ResourceManager.GetString("TabItem_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензия отсутствует.
        /// </summary>
        public static string TextBlock_EmptyLicense {
            get {
                return ResourceManager.GetString("TextBlock_EmptyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ид. номер:.
        /// </summary>
        public static string TextBlock_Id {
            get {
                return ResourceManager.GetString("TextBlock_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TextBlock_LastLog {
            get {
                return ResourceManager.GetString("TextBlock_LastLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус лицензии:.
        /// </summary>
        public static string TextBlock_LicenseStatus {
            get {
                return ResourceManager.GetString("TextBlock_LicenseStatus", resourceCulture);
            }
        }
    }
}
